services:
  nginx:
    image: 'nginx:alpine'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "app"
    networks:
      - "app-network"
    volumes:
      - "${SSH_CONFIG_PATH}/nginx.prod.conf:/etc/nginx/nginx.conf:ro"
      - "${SSL_PATH}:${SSL_PATH}:ro"

  app:
    image: "ghcr.io/ardxel/web-git-analyzer:${APP_TAG}"
    container_name: app
    expose:
      - "8000"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - "redis"
    networks:
      - app-network
    environment:
      - GO_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIN_PORT=8000
      - DEBUG=1
      - MAX_DISK_SIZE     
      - MAX_REPO_SIZE 
      - SYNC_EVERY
      - USE_FILE_WORKERS
      - API_PAT


  redis:
    image: "redis:alpine"
    container_name: redis
    expose:
      - "6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
