services:
  app:
    image: 'ghcr.io/ardxel/web-git-analyzer:${APP_TAG}'
    container_name: app
    ports: 
      - '80:80'
    depends_on:
      - 'redis'
    networks:
      - app-network
    environment:
      - GO_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIN_PORT=80
      - DEBUG=1
      - MAX_DISK_SIZE     
      - MAX_REPO_SIZE 
      - SYNC_EVERY
      - USE_FILE_WORKERS

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports: 
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


