services:
  app:
    build: 
      context: '../'
      dockerfile: './.docker/Dockerfile'
    ports: 
      - '8000:8000'
    depends_on:
      - 'redis'
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    ports: 
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


