name: Deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository_owner }}/web-git-analyzer"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./.docker/Dockerfile.build
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: ["publish"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy docker compose via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".docker/docker-compose.prod.yml,.docker/nginx.prod.conf"
          target: ${{ secrets.SSH_CONFIG_PATH }}
          strip_components: 1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        env:
          MAX_DISK_SIZE: ${{ vars.MAX_DISK_SIZE }}
          MAX_REPO_SIZE: ${{ vars.MAX_REPO_SIZE }}
          SYNC_EVERY: ${{ vars.SYNC_EVERY }}
          USE_FILE_WORKERS: ${{ vars.USE_FILE_WORKERS }}
          APP_TAG: latest
          SSH_CONFIG_PATH: ${{ secrets.SSH_CONFIG_PATH }}
          SSL_PATH: ${{ secrets.SSL_PATH }}
          API_PAT: ${{ secrets.API_PAT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: MAX_DISK_SIZE,MAX_REPO_SIZE,SYNC_EVERY,USE_FILE_WORKERS,APP_TAG, SSH_CONFIG_PATH, SSL_PATH, API_PAT
          script: |
            cd "$SSH_CONFIG_PATH"
            docker-compose -f ./docker-compose.prod.yml down
            docker-compose -f ./docker-compose.prod.yml pull
            docker-compose -f ./docker-compose.prod.yml up -d

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.1.0
        env:
          SSH_CONFIG_PATH: ${{ secrets.SSH_CONFIG_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SSH_CONFIG_PATH
          script: |
            docker ps -a
            docker-compose -f "${SSH_CONFIG_PATH}/docker-compose.prod.yml" logs app
