name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            touch ~/.deploy 
            echo 'SUCCESS' > ~/.deploy
