name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
    - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          docker build -f ./.docker/Dockerfile.build -t ghcr.io/${{ github.actor }}/web-git-analyzer:${{ github.sha }} .
          docker push ghcr.io/${{ github.actor }}/web-git-analyzer:${{ github.sha }}

  deploy:
    needs: ["publish"]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Copy docker compose via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".docker/docker-compose.prod.yml,.docker/nginx.prod.conf"
        target: ${{ secrets.SSH_CONFIG_PATH }}
        strip_components: 1

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.1.0
      env:
        MAX_DISK_SIZE: ${{ vars.MAX_DISK_SIZE }}
        MAX_REPO_SIZE: ${{ vars.MAX_REPO_SIZE }}
        SYNC_EVERY: ${{ vars.SYNC_EVERY }}
        USE_FILE_WORKERS: ${{ vars.USE_FILE_WORKERS }}
        APP_TAG: ${{ github.sha }}
        SSH_CONFIG_PATH: ${{ secrets.SSH_CONFIG_PATH }}
        SSL_PATH: ${{ vars.SSL_PATH }}
        
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: MAX_DISK_SIZE,MAX_REPO_SIZE,SYNC_EVERY,USE_FILE_WORKERS,APP_TAG, SSH_CONFIG_PATH, SSL_PATH
        script: |
          cd "$SSH_CONFIG_PATH"
          docker-compose -f ./docker-compose.prod.yml down
          docker-compose -f ./docker-compose.prod.yml pull
          docker-compose -f ./docker-compose.prod.yml up -d

    - name: Verify deployment
      uses: appleboy/ssh-action@v1.1.0
      env:
        SSH_CONFIG_PATH: ${{ secrets.SSH_CONFIG_PATH }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: SSH_CONFIG_PATH
        script: |
          docker ps -a
          docker-compose -f "${SSH_CONFIG_PATH}/docker-compose.prod.yml" logs app
