name: Deploy

on:
  push:
    branches:
      - main
      - test-workflow
  pull_request:
    branches:
      - main
      - test-workflow
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debugging workflow_run
      run: |
        echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"

    - name: Set up SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            touch ~/.deploy 
            echo 'SUCCESS' > ~/.deploy
